export const ErrorCode = {
  ApprovalRequired: 'APPROVAL_REQUIRED',
  ApkInstallFailed: 'APK_INSTALL_FAILED',
  ApkInvalid: 'APK_INVALID',
  CommandFailed: 'COMMAND_FAILED',
  CommandOutputLimit: 'COMMAND_OUTPUT_LIMIT',
  CommandTimeout: 'COMMAND_TIMEOUT',
  ConfigurationInvalid: 'CONFIGURATION_INVALID',
  DeviceDisconnected: 'DEVICE_DISCONNECTED',
  DeviceNotFound: 'DEVICE_NOT_FOUND',
  DeviceOffline: 'DEVICE_OFFLINE',
  DeviceUnauthorized: 'DEVICE_UNAUTHORIZED',
  ExecutableNotFound: 'EXECUTABLE_NOT_FOUND',
  EvidencePathInvalid: 'EVIDENCE_PATH_INVALID',
  FileNotAllowed: 'FILE_NOT_ALLOWED',
  ForegroundUnknown: 'FOREGROUND_UNKNOWN',
  InvalidCoordinates: 'INVALID_COORDINATES',
  InvalidInput: 'INVALID_INPUT',
  InvalidPackage: 'INVALID_PACKAGE',
  InvalidPath: 'INVALID_PATH',
  InvalidSelector: 'INVALID_SELECTOR',
  InvalidSerial: 'INVALID_SERIAL',
  MultipleDevices: 'MULTIPLE_DEVICES',
  NoDeviceSelected: 'NO_DEVICE_SELECTED',
  PackageNotAllowed: 'PACKAGE_NOT_ALLOWED',
  PermissionNotRequested: 'PERMISSION_NOT_REQUESTED',
  ProhibitedOperation: 'PROHIBITED_OPERATION',
  ScrcpyAlreadyRunning: 'SCRCPY_ALREADY_RUNNING',
  ScrcpyNotFound: 'SCRCPY_NOT_FOUND',
  ScrcpyNotOwned: 'SCRCPY_NOT_OWNED',
  ScreenshotInvalid: 'SCREENSHOT_INVALID',
  ScreenshotTooLarge: 'SCREENSHOT_TOO_LARGE',
  SensitivePackage: 'SENSITIVE_PACKAGE',
  SessionConflict: 'SESSION_CONFLICT',
  StaleUiSnapshot: 'STALE_UI_SNAPSHOT',
  UiElementAmbiguous: 'UI_ELEMENT_AMBIGUOUS',
  UiElementNotFound: 'UI_ELEMENT_NOT_FOUND',
  UiHierarchyIncomplete: 'UI_HIERARCHY_INCOMPLETE',
  UnsupportedOperation: 'UNSUPPORTED_OPERATION',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
